CREATE TABLE IF NOT EXISTS stock_images (
  image_key TEXT PRIMARY KEY,
  content_type TEXT NOT NULL,
  etag TEXT NOT NULL,
  data BLOB NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
