type Kind='cars'|'goods'; type Row=Record<string,any>;
const root=document.querySelector<HTMLDivElement>('#admin')!;let kind:Kind='cars',rows:Row[]=[];
root.innerHTML=`<header class="top"><h1>マナエンタープライズ（株）在庫管理</h1><a href="/" target="_blank">公開サイト ↗</a></header><main class="wrap"><div class="tabs"><button data-kind="cars" class="active">中古車</button><button data-kind="goods">家具・家電</button></div><section class="panel"><div class="toolbar"><div><small>INVENTORY</small><h2 id="title">中古車</h2></div><button class="primary" id="new">＋ 新規登録</button></div><div id="list"></div></section></main><dialog id="modal"><form id="form"><h2 id="formTitle"></h2><div id="fields"></div><p class="notice">写真はJPEG・PNG・WebP。選択時に長辺1200px・品質75%へ圧縮し、1MB以下で保存します。</p><label>商品写真（任意）<input id="image" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="form-actions"><button type="button" id="cancel">キャンセル</button><button class="primary">保存して公開</button></div></form></dialog>`;
const listEl=document.querySelector<HTMLDivElement>('#list')!,modal=document.querySelector<HTMLDialogElement>('#modal')!,form=document.querySelector<HTMLFormElement>('#form')!;
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function request<T=any>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);if(!r.ok)throw Error(await r.text());return r.json() as Promise<T>;}
async function load(){listEl.innerHTML='読み込み中…';try{rows=await request<Row[]>(`/admin/api/${kind}`);render();}catch{listEl.innerHTML='<p class="empty">在庫を読み込めませんでした。Accessの設定をご確認ください。</p>';}}
function imagePath(key:string){return key.split('/').map(encodeURIComponent).join('/');}
function render(){listEl.innerHTML=rows.length?rows.map(x=>`<div class="item">${x.image_key?`<img src="/images/${imagePath(x.image_key)}?v=2" alt="">`:'<span class="thumb"></span>'}<div><strong>${esc(x.name)}</strong><p>${esc(x.category)}｜${esc(x.status)}｜表示順 ${x.display_order}</p></div><div class="actions"><button data-edit="${x.id}">編集</button><button class="danger" data-delete="${x.id}">削除</button></div></div>`).join(''):'<p class="empty">登録された在庫はありません。</p>';}
function fields(row:Row={}){const common=`<div class="form-grid"><label>名称 *<input name="name" required value="${esc(row.name)}"></label><label>カテゴリ *<input name="category" required value="${esc(row.category)}"></label>`;return common+(kind==='cars'?`<label>年式<input name="model_year" type="number" value="${esc(row.model_year)}"></label><label>走行距離（km）<input name="mileage" type="number" value="${esc(row.mileage)}"></label>`:`<label>商品の状態<input name="condition" value="${esc(row.condition)}"></label><label>サイズ・説明<textarea name="description">${esc(row.description)}</textarea></label>`)+`<label>価格（円）<input name="price" type="number" min="0" required value="${esc(row.price||0)}"></label><label>販売状態<select name="status">${(kind==='cars'?['販売中','売約済み','販売済み']:['販売中','取置中','販売済み']).map(s=>`<option ${row.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>表示順<input name="display_order" type="number" value="${esc(row.display_order||0)}"></label></div><input type="hidden" name="id" value="${esc(row.id)}">`;}
function open(row?:Row){document.querySelector('#formTitle')!.textContent=row?'在庫を編集':'新規登録';document.querySelector('#fields')!.innerHTML=fields(row);(document.querySelector('#image') as HTMLInputElement).value='';modal.showModal();}
async function compress(file:File){const bmp=await createImageBitmap(file),scale=Math.min(1,1200/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);canvas.getContext('2d')!.drawImage(bmp,0,0,canvas.width,canvas.height);const type=file.type==='image/png'?'image/png':file.type==='image/webp'?'image/webp':'image/jpeg';const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(),type,.75));if(blob.size>1024*1024)throw Error('圧縮後も1MBを超えています。別の画像を選んでください。');return blob;}
form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),id=String(fd.get('id')||''),data=Object.fromEntries(fd);delete data.id;try{const saved=await request(`/admin/api/${kind}${id?'/'+id:''}`,{method:id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const file=(document.querySelector('#image') as HTMLInputElement).files?.[0];if(file){const blob=await compress(file);await request(`/admin/api/upload/${kind}/${saved.id}`,{method:'POST',headers:{'content-type':blob.type},body:blob});}modal.close();await load();}catch(e){alert(`保存できませんでした: ${e}`);}});
root.addEventListener('click',async e=>{const t=e.target as HTMLElement;if(t.dataset.kind){kind=t.dataset.kind as Kind;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.kind===kind));document.querySelector('#title')!.textContent=kind==='cars'?'中古車':'家具・家電';load();}if(t.id==='new')open();if(t.dataset.edit)open(rows.find(x=>x.id==t.dataset.edit));if(t.dataset.delete){const x=rows.find(r=>r.id==t.dataset.delete);if(x&&confirm(`「${x.name}」を削除しますか？\nこの操作では対応する画像も削除されます。`)){try{await request(`/admin/api/${kind}/${x.id}`,{method:'DELETE'});load();}catch{alert('削除できませんでした');}}}if(t.id==='cancel')modal.close();});load();
