import {store,yen} from './config';
import './no-manager.css';
import './logo-size.css';
import './reference-layout.css';
type Item=Record<string,any>;
const app=document.querySelector<HTMLDivElement>('#app')!;
const header=`<header><a class="brand" href="/"><img src="/assets/logo.png" onerror="this.onerror=null;this.src='/assets/logo-placeholder.svg'" alt="MANA ENTERPRISES"><span>${store.name}</span></a><nav><a href="/">中古車</a><a href="/furniture-appliances">家具・家電</a><a href="#contact">お問い合わせ</a></nav></header>`;
const footer=`<footer><strong>${store.name}</strong><span>${store.english}</span><small>© ${new Date().getFullYear()} MANA ENTERPRISES</small></footer>`;
const contact=`<section class="contact" id="contact"><p class="eyebrow">CONTACT</p><h2>お問い合わせはInstagramへ</h2><p>在庫確認、買取、取り置き、配達についてDMでご相談ください。</p><div class="contact-grid"><span>◎ ${store.phone}</span><span>◷ ${store.hours}</span><span>⌖ ${store.address}</span></div></section>`;
const badge=(s:string)=>s==='販売中'?`<span class="badge live">${s}</span>`:`<span class="badge closed">${s}</span>`;
const img=(x:Item)=>x.image_key?`<img loading="lazy" src="/images/${encodeURIComponent(x.image_key)}" alt="${x.name}">`:`<div class="no-image">写真準備中</div>`;
const cards=(items:Item[],kind:'cars'|'goods')=>items.map(x=>`<article class="card"><div class="photo">${img(x)}${badge(x.status)}</div><div class="card-body"><p class="category">${x.category}</p><h3>${x.name}</h3>${kind==='cars'?`<p>${x.model_year||'—'}年式・走行 ${x.mileage?new Intl.NumberFormat('ja-JP').format(x.mileage)+'km':'—'}</p>`:`<p>${x.condition}</p><p>${x.description}</p>`}<strong class="price">${yen(x.price)}</strong></div></article>`).join('');
async function get(path:string):Promise<Item[]>{const r=await fetch(path);if(!r.ok)throw Error();return r.json() as Promise<Item[]>;}
function shell(content:string){content=content.replace('<h3>中古車販売</h3>','<h3>中古車買取・販売</h3>').replace('中古家具・中古家電販売','中古家具・家電買取・販売').replace('<h1>暮らしにちょうどいい、','<h1>中古家具・家電買取・販売<br><small>暮らしにちょうどいい、').replace('手頃な家具・家電。</h1><p>一点もの','手頃な家具・家電。</small></h1><p>一点もの');app.innerHTML=header.replace('/assets/logo.png','/assets/header-logo-reference.png')+`<main>${content}</main>`+footer;}
async function home(){shell(`<section class="hero"><div><p class="eyebrow">USED CARS & FRIENDLY SERVICE</p><h1>ちょうどいい一台を、<br>いっしょに。</h1><p>兵庫県の小さな中古販売店。購入も買取も、わかりやすく親身にお手伝いします。</p><a class="button" href="#stock">在庫車を見る</a></div><div class="hero-art"><span>🚗</span><b>安心して相談できる<br>身近なクルマ屋さん</b></div></section><section id="stock"><p class="eyebrow">RECOMMENDED</p><h2>おすすめ中古車</h2><div class="grid" id="list"><p>読み込み中…</p></div></section><section class="services"><div><b>01</b><h3>中古車販売</h3><p>ご予算や暮らしに合う一台を一緒に探します。</p></div><div><b>02</b><h3>買取</h3><p>乗り換えや手放しのご相談も歓迎です。</p></div><div><b>03</b><h3>購入後の相談</h3><p>購入後も困ったことを気軽に相談できます。</p></div></section><a class="wide-link" href="/furniture-appliances"><span>家具・家電も手頃に</span><strong>中古家具・家電を見る →</strong></a><section class="manager"><div class="portrait"><img src="/assets/manager.jpg" alt="店長" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span>店長写真<br>準備中</span></div><div><p class="eyebrow">SHOP MANAGER</p><h2>店長からごあいさつ</h2><p>地域のみなさまに気軽に立ち寄っていただけるお店を目指しています。クルマも家具・家電も、わからないことからご相談ください。</p></div></section><section><p class="eyebrow">HOW TO BUY</p><h2>中古車購入までの流れ</h2><ol class="steps"><li><b>1</b><span>お問い合わせ・在庫確認</span></li><li><b>2</b><span>ご来店・車両確認</span></li><li><b>3</b><span>お見積り・ご契約</span></li><li><b>4</b><span>整備・納車</span></li></ol></section>${contact}<section class="company"><h2>会社情報</h2><dl><dt>社名</dt><dd>${store.name}</dd><dt>英語表記</dt><dd>${store.english}</dd><dt>事業内容</dt><dd>中古車販売・買取<br>中古家具・中古家電販売</dd><dt>所在地</dt><dd>${store.address}</dd></dl></section>`);try{const data=await get('/api/cars');document.querySelector('#list')!.innerHTML=data.length?cards(data,'cars'):'<p class="empty">車両を入荷次第、こちらに掲載します</p>';}catch{document.querySelector('#list')!.innerHTML='<p class="empty">在庫情報を読み込めませんでした。しばらくしてからお試しください。</p>';}}
async function goods(){shell(`<section class="subhero"><p class="eyebrow">FURNITURE & APPLIANCES</p><h1>暮らしにちょうどいい、<br>手頃な家具・家電。</h1><p>一点ものの中古品を、状態を確認してご案内します。</p></section><section><h2>家具・家電の在庫</h2><div class="grid" id="list"><p>読み込み中…</p></div></section><section class="services"><div><b>01</b><h3>在庫を確認</h3><p>掲載商品についてお問い合わせください。</p></div><div><b>02</b><h3>商品を確認</h3><p>ご来店いただき、状態をご確認ください。</p></div><div><b>03</b><h3>購入・受け取り</h3><p>取り置きや配達もご相談いただけます。</p></div></section>${contact}`);try{const data=await get('/api/goods');document.querySelector('#list')!.innerHTML=data.length?cards(data,'goods'):'<p class="empty">商品を入荷次第、こちらに掲載します</p>';}catch{document.querySelector('#list')!.innerHTML='<p class="empty">商品を入荷次第、こちらに掲載します</p>';}}
location.pathname.startsWith('/furniture-appliances')?goods():home();
